export const BROAD_FAMILIES = [
  // bakery
  ['english muffins','English muffins'],['pita bread','Pita bread'],['naan','Naan'],['croissants','Croissants'],
  ['baguette','Baguette'],['sourdough bread','Sourdough bread'],['hamburger buns','Hamburger buns'],
  ['hot dog buns','Hot dog buns'],['dinner rolls','Dinner rolls'],['donuts','Donuts'],['muffins','Muffins'],
  ['brownies','Brownies'],['wraps','Wraps'],['flatbread','Flatbread'],['rye bread','Rye bread'],
  ['brioche','Brioche'],['ciabatta','Ciabatta'],['pretzel buns','Pretzel buns'],['bread crumbs','Breadcrumbs'],
  // international
  ['tempeh','Tempeh'],['seitan','Seitan'],['nori','Nori'],['seaweed sheets','Nori'],['rice paper','Rice paper'],
  ['wonton wrappers','Wonton wrappers'],['dumpling wrappers','Dumpling wrappers'],['dumplings','Dumplings'],
  ['potstickers','Dumplings'],['gyoza','Gyoza'],['paneer','Paneer'],['dal','Dal'],['red lentils','Dal'],
  ['split lentils','Dal'],['chickpea flour','Chickpea flour'],['besan','Chickpea flour'],
  ['tamarind paste','Tamarind paste'],['masa harina','Masa harina'],['queso fresco','Queso fresco'],
  ['cotija','Cotija'],['falafel','Falafel'],['pierogi','Pierogi'],['spring rolls','Spring rolls'],
  ['egg rolls','Spring rolls'],['bao','Bao'],['rice flour','Rice flour'],['coconut flour','Coconut flour'],
  ['curry leaves','Curry leaves'],['plantains','Plantains'],['yuca','Yuca'],['cassava','Yuca'],
  // breakfast
  ['pancake mix','Pancake mix'],['waffle mix','Pancake mix'],['breakfast sausage','Breakfast sausage'],
  ['instant oatmeal','Instant oatmeal'],['toaster pastries','Toaster pastries'],
  ['frozen breakfast sandwiches','Frozen breakfast sandwiches'],['yogurt drinks','Yogurt drinks'],
  ['drinkable yogurt','Yogurt drinks'],['granola bars','Granola bars'],['breakfast cereal','Breakfast cereal'],
  // grains and pasta
  ['lasagna noodles','Lasagna noodles'],['ramen','Ramen'],['rice noodles','Rice noodles'],['udon','Udon'],
  ['soba','Soba'],['couscous','Couscous'],['farro','Farro'],['barley','Barley'],['bulgur','Bulgur'],
  ['brown rice','Brown rice'],['jasmine rice','Jasmine rice'],['basmati rice','Basmati rice'],
  ['arborio rice','Arborio rice'],['wild rice','Wild rice'],['polenta','Polenta'],['gnocchi','Gnocchi'],
  ['orzo','Orzo'],['egg noodles','Egg noodles'],['quinoa','Quinoa'],['fresh pasta','Fresh pasta'],
  ['macaroni','Pasta'],['elbow pasta','Pasta'],['spaghetti','Pasta'],['penne','Pasta'],
  // snacks
  ['tortilla chips','Tortilla chips'],['pretzels','Pretzels'],['protein bars','Protein bars'],
  ['trail mix','Trail mix'],['cashews','Cashews'],['peanuts','Peanuts'],['pecans','Pecans'],
  ['raisins','Raisins'],['dried cranberries','Dried cranberries'],['dried apricots','Dried apricots'],
  ['rice cakes','Rice cakes'],['candy','Candy'],['chocolate bars','Chocolate bars'],['gum','Gum'],
  ['fruit snacks','Fruit snacks'],['applesauce','Applesauce'],['pudding cups','Pudding cups'],
  ['gelatin cups','Gelatin cups'],['beef jerky','Beef jerky'],['seaweed snacks','Seaweed snacks'],
  ['pita chips','Pita chips'],['veggie straws','Veggie straws'],['popcorn','Popcorn kernels'],
  ['mixed nuts','Mixed nuts'],['sunflower seeds','Sunflower seeds'],['pumpkin seeds','Pumpkin seeds'],
  // condiments and sauces
  ['fish sauce','Fish sauce'],['ranch dressing','Ranch dressing'],
  ['blue cheese dressing','Blue cheese dressing'],['italian dressing','Italian dressing'],
  ['vinaigrette','Vinaigrette'],['dijon mustard','Dijon mustard'],['relish','Relish'],['tahini','Tahini'],
  ['miso','Miso'],['gochujang','Gochujang'],['harissa','Harissa'],['pesto','Pesto'],
  ['marinara sauce','Marinara sauce'],['alfredo sauce','Alfredo sauce'],['curry paste','Curry paste'],
  ['teriyaki sauce','Teriyaki sauce'],['sesame oil','Sesame oil'],['coconut oil','Coconut oil'],
  ['avocado oil','Avocado oil'],['vegetable oil','Vegetable oil'],['canola oil','Canola oil'],
  ['rice vinegar','Rice vinegar'],['nutritional yeast','Nutritional yeast'],['chili crisp','Chili crisp'],
  ['buffalo sauce','Buffalo sauce'],['steak sauce','Steak sauce'],['cocktail sauce','Cocktail sauce'],
  ['tartar sauce','Tartar sauce'],['horseradish','Horseradish'],['wasabi','Wasabi powder'],
  ['chili paste','Chili paste'],['sambal','Chili paste'],['enchilada sauce','Enchilada sauce'],
  ['tzatziki','Tzatziki'],['chimichurri','Chimichurri'],
  // canned
  ['kidney beans','Kidney beans'],['pinto beans','Pinto beans'],['cannellini beans','Cannellini beans'],
  ['refried beans','Refried beans'],['baked beans','Baked beans'],['tomato sauce','Tomato sauce'],
  ['crushed tomatoes','Crushed tomatoes'],['canned pumpkin','Canned pumpkin'],['jackfruit','Jackfruit'],
  ['canned soup','Canned soup'],['green chiles','Green chiles'],['coconut cream','Coconut cream (canned)'],
  ['beef broth','Beef broth'],['vegetable broth','Vegetable broth'],['bone broth','Bone broth'],
  ['canned peaches','Canned peaches'],['canned pineapple','Canned pineapple'],
  ['canned mushrooms','Canned mushrooms'],['canned green beans','Canned green beans'],
  ['canned peas','Canned peas'],['canned carrots','Canned carrots'],['canned chili','Canned chili'],
  ['canned chicken','Canned chicken'],
  // baking
  ['bread flour','Bread flour'],['whole wheat flour','Whole wheat flour'],['almond flour','Almond flour'],
  ['cake flour','Cake flour'],['baking powder','Baking powder'],['active dry yeast','Active dry yeast'],
  ['instant yeast','Active dry yeast'],['cocoa powder','Cocoa powder'],['brown sugar','Brown sugar'],
  ['powdered sugar','Powdered sugar'],['molasses','Molasses'],['gelatin','Gelatin'],['sprinkles','Sprinkles'],
  ['sweetened condensed milk','Sweetened condensed milk'],['shortening','Shortening'],['pie crust','Pie crust'],
  ['puff pastry','Puff pastry'],['phyllo dough','Phyllo dough'],['food coloring','Food coloring'],
  ['baking chocolate','Baking chocolate'],['panko','Breadcrumbs'],['cornbread mix','Cornbread mix'],
  ['cake mix','Cake mix'],['brownie mix','Brownie mix'],['coconut flakes','Coconut flakes'],
  // dairy and cheese
  ['whipped cream','Whipped cream'],['feta','Feta'],['goat cheese','Goat cheese'],['provolone','Provolone'],
  ['pepper jack','Pepper jack'],['american cheese','American cheese'],['gouda','Gouda'],
  ['blue cheese','Blue cheese'],['kefir','Kefir'],['shredded cheese','Shredded cheese'],
  ['half and half','Half and half'],['heavy cream','Heavy cream'],['cottage cheese','Cottage cheese'],
  ['swiss cheese','Swiss cheese'],['string cheese','String cheese'],['egg whites','Egg whites'],
  ['ghee','Ghee'],['brie','Brie'],['monterey jack','Monterey jack'],['colby jack','Colby jack'],
  ['queso blanco','Queso blanco'],['sour cream','Sour cream'],['buttermilk','Buttermilk'],
  ['whipped topping','Whipped topping'],
  // meat
  ['chicken wings','Chicken wings'],['chicken drumsticks','Chicken drumsticks'],['chicken thighs','Chicken thighs'],
  ['whole chicken','Whole chicken'],['ground chicken','Ground chicken'],['ground turkey','Ground turkey'],
  ['ground pork','Ground pork'],['pork tenderloin','Pork tenderloin'],['pork shoulder','Pork shoulder'],
  ['pork belly','Pork belly'],['pork ribs','Pork ribs'],['brisket','Brisket'],['lamb chops','Lamb chops'],
  ['ground lamb','Ground lamb'],['veal','Veal'],['bratwurst','Bratwurst'],['chorizo','Chorizo'],
  ['kielbasa','Kielbasa'],['meatballs','Meatballs'],['stew meat','Stew meat'],['beef roast','Beef roast'],
  ['hot dogs','Hot dogs'],['turkey breast','Turkey breast'],['pork chops','Pork chops'],['bison','Bison'],
  ['duck','Duck'],
  // deli and prepared
  ['prosciutto','Prosciutto'],['salami','Salami'],['sushi','Sushi'],['potato salad','Potato salad'],
  ['coleslaw','Coleslaw'],['rotisserie chicken','Rotisserie chicken'],['deli roast beef','Deli roast beef'],
  ['deli chicken','Deli chicken'],['pepperoni','Pepperoni'],['guacamole','Guacamole'],
  ['macaroni salad','Macaroni salad'],['chicken salad','Chicken salad'],['egg salad','Egg salad'],
  // produce
  ['clementines','Clementines'],['parsnips','Parsnips'],['shallots','Shallots'],['jalapenos','Jalapenos'],
  ['jalapeños','Jalapenos'],['serrano peppers','Serrano peppers'],['poblano peppers','Poblano peppers'],
  ['snap peas','Snap peas'],['romaine','Romaine'],['mixed greens','Mixed greens'],['spring mix','Mixed greens'],
  ['microgreens','Microgreens'],['figs','Figs'],['tomatillos','Tomatillos'],['nectarines','Nectarines'],
  ['apricots','Apricots'],['honeydew','Honeydew'],['cantaloupe','Cantaloupe'],['radishes','Radishes'],
  ['turnips','Turnips'],['beets','Beets'],['leeks','Leeks'],['fennel','Fennel'],['endive','Endive'],
  ['watercress','Watercress'],['chard','Swiss chard'],['collard greens','Collard greens'],['okra','Okra'],
  ['rhubarb','Rhubarb'],['persimmons','Persimmons'],['passion fruit','Passion fruit'],
  ['dragon fruit','Dragon fruit'],['papaya','Papaya'],['guava','Guava'],['lychee','Lychee'],
  ['starfruit','Starfruit'],
  // rows the families name that an existing row already answers
  ['green onions','Green onions'],['veggie burger','Veggie burgers'],
];
export const BROAD_APPLIED_FAMILIES = [
  ['scallions','Green onions'],['bbq sauce','Barbecue sauce'],
  ['chopped walnuts','Walnuts'],['pepitas','Pumpkin seeds'],['plant-based burger','Veggie burgers'],
];
export const BROAD_PROBES = [
  ['english muffin','English muffins'],['naan','Naan'],['potstickers','Dumplings'],['paneer','Paneer'],
  ['pancake mix','Pancake mix'],['ramen','Ramen'],['basmati','Basmati rice'],['cashews','Cashews'],
  ['jerky','Jerky'],['fish sauce','Fish sauce'],['ranch','Ranch dressing'],['pinto beans','Pinto beans'],
  ['bread flour','Bread flour'],['feta','Feta'],['chicken wings','Chicken wings'],['prosciutto','Prosciutto'],
  ['jalapeño','Jalapenos'],['jalapeno','Jalapenos'],['spring mix','Mixed greens'],
];
