-- GENERATED by scripts/build-neon-baseline.mjs — the privilege model from
-- db/neon-baseline.sql, extracted so it can be re-applied on its own after
-- Neon's Data API provisioning recreates the anon/authenticated roles.
-- Idempotent: GRANT/REVOKE are declarative.
--
-- Three sections, and THE ORDER IS LOAD-BEARING:
--   1. Client-role lines, verbatim from the baseline.
--   2. Every `service_role` statement, in one role-exists-guarded block
--      (audit 2026-08-22, SEC-13) — the role only exists once Data API
--      provisioning has run.
--   3. Below the HAND-MAINTAINED TAIL marker: the privilege decisions of
--      migrations past the squash line (audit SCH-02/SCH-03). The generator
--      preserves the tail verbatim on every run — new migrations that issue
--      GRANT/REVOKE append their statements there by hand. The tail NARROWS
--      grants section 1 still carries (0001's blanket GRANTs), so it must
--      stay last: appended after, never inserted before.

GRANT USAGE ON SCHEMA public TO anonymous;
GRANT USAGE ON SCHEMA public TO authenticated;
REVOKE ALL ON FUNCTION public.assert_item_location_scope() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.claim_ai_call(p_user uuid, p_kind text, p_free_monthly integer, p_plus_monthly integer, p_daily_cap integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.clear_stale_out_items(p_household_id uuid) FROM PUBLIC;
GRANT ALL ON FUNCTION public.clear_stale_out_items(p_household_id uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.create_catalog_item(p_user uuid, p_name text, p_category public.food_category, p_shelf_life jsonb, p_barcodes text[], p_nutrition jsonb, p_source text, p_daily_cap integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_household(p_name text) FROM PUBLIC;
GRANT ALL ON FUNCTION public.create_household(p_name text) TO authenticated;
GRANT ALL ON FUNCTION public.handle_new_user() TO anonymous;
GRANT ALL ON FUNCTION public.handle_new_user() TO authenticated;
GRANT ALL ON FUNCTION public.is_household_member(h uuid) TO anonymous;
GRANT ALL ON FUNCTION public.is_household_member(h uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.is_household_owner(h uuid) FROM PUBLIC;
GRANT ALL ON FUNCTION public.is_household_owner(h uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.join_household(p_code text) FROM PUBLIC;
GRANT ALL ON FUNCTION public.join_household(p_code text) TO authenticated;
REVOKE ALL ON FUNCTION public.merge_add_items(p_household_id uuid, p_items jsonb) FROM PUBLIC;
GRANT ALL ON FUNCTION public.merge_add_items(p_household_id uuid, p_items jsonb) TO authenticated;
REVOKE ALL ON FUNCTION public.normalize_item_name(p_name text) FROM PUBLIC;
GRANT ALL ON FUNCTION public.normalize_item_name(p_name text) TO authenticated;
REVOKE ALL ON FUNCTION public.refund_ai_call(p_user uuid, p_claim uuid) FROM PUBLIC;
GRANT ALL ON FUNCTION public.set_updated_at() TO anonymous;
GRANT ALL ON FUNCTION public.set_updated_at() TO authenticated;
GRANT ALL ON FUNCTION public.shares_household_with(other uuid) TO anonymous;
GRANT ALL ON FUNCTION public.shares_household_with(other uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.transfer_household_ownership(p_household uuid, p_new_owner uuid) FROM PUBLIC;
GRANT ALL ON FUNCTION public.transfer_household_ownership(p_household uuid, p_new_owner uuid) TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.ai_calls TO anonymous;
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.ai_calls TO authenticated;
GRANT ALL ON TABLE public.catalog_items TO anonymous;
GRANT ALL ON TABLE public.catalog_items TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.entitlements TO anonymous;
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.entitlements TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.grocery_items TO anonymous;
GRANT ALL ON TABLE public.grocery_items TO authenticated;
GRANT ALL ON TABLE public.household_members TO anonymous;
GRANT ALL ON TABLE public.household_members TO authenticated;
GRANT ALL ON TABLE public.households TO anonymous;
GRANT ALL ON TABLE public.households TO authenticated;
GRANT ALL ON TABLE public.inventory_items TO anonymous;
GRANT ALL ON TABLE public.inventory_items TO authenticated;
GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE public.profiles TO anonymous;
GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE public.profiles TO authenticated;
GRANT SELECT(id) ON TABLE public.profiles TO authenticated;
GRANT SELECT(display_name) ON TABLE public.profiles TO authenticated;
GRANT SELECT(avatar_url) ON TABLE public.profiles TO authenticated;
GRANT SELECT(notify_digest) ON TABLE public.profiles TO authenticated;
GRANT SELECT(created_at) ON TABLE public.profiles TO authenticated;
GRANT ALL ON TABLE public.recipe_ingredients TO anonymous;
GRANT ALL ON TABLE public.recipe_ingredients TO authenticated;
GRANT ALL ON TABLE public.recipe_reports TO anonymous;
GRANT ALL ON TABLE public.recipe_reports TO authenticated;
GRANT ALL ON TABLE public.recipe_saves TO anonymous;
GRANT ALL ON TABLE public.recipe_saves TO authenticated;
GRANT ALL ON TABLE public.recipes TO anonymous;
GRANT ALL ON TABLE public.recipes TO authenticated;
GRANT ALL ON TABLE public.storage_locations TO anonymous;
GRANT ALL ON TABLE public.storage_locations TO authenticated;
GRANT ALL ON TABLE public.zones TO anonymous;
GRANT ALL ON TABLE public.zones TO authenticated;

-- service_role (audit 2026-08-22, SEC-13) -----------------------------------
--
-- Every `service_role` statement from the baseline, in one guarded block —
-- "what does the service identity hold" is one place to read. The role is
-- created by Neon's Data API provisioning, so on a bare database it does not
-- exist yet and an unguarded GRANT here aborted the whole file — the same
-- reason db/neon-bootstrap.sql:105-118 guards its own grants. Grants for
-- post-squash objects live in the hand-maintained tail below.
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    raise notice 'role service_role not present (Data API not provisioned) — skipping';
    return;
  end if;

  grant usage on schema public to service_role;

  grant all on function public.claim_ai_call(p_user uuid, p_kind text, p_free_monthly integer, p_plus_monthly integer, p_daily_cap integer) to service_role;
  grant all on function public.clear_stale_out_items(p_household_id uuid) to service_role;
  grant all on function public.create_catalog_item(p_user uuid, p_name text, p_category public.food_category, p_shelf_life jsonb, p_barcodes text[], p_nutrition jsonb, p_source text, p_daily_cap integer) to service_role;
  grant all on function public.create_household(p_name text) to service_role;
  grant all on function public.handle_new_user() to service_role;
  grant all on function public.is_household_member(h uuid) to service_role;
  grant all on function public.join_household(p_code text) to service_role;
  grant all on function public.merge_add_items(p_household_id uuid, p_items jsonb) to service_role;
  grant all on function public.normalize_item_name(p_name text) to service_role;
  grant all on function public.refund_ai_call(p_user uuid, p_claim uuid) to service_role;
  grant all on function public.set_updated_at() to service_role;
  grant all on function public.shares_household_with(other uuid) to service_role;

  grant all on table public.ai_calls to service_role;
  grant all on table public.catalog_items to service_role;
  grant all on table public.entitlements to service_role;
  grant all on table public.grocery_items to service_role;
  grant all on table public.household_members to service_role;
  grant all on table public.households to service_role;
  grant all on table public.inventory_items to service_role;
  grant all on table public.profiles to service_role;
  grant all on table public.recipe_ingredients to service_role;
  grant all on table public.recipe_reports to service_role;
  grant all on table public.recipe_saves to service_role;
  grant all on table public.recipes to service_role;
  grant all on table public.storage_locations to service_role;
  grant all on table public.zones to service_role;
end $$;

-- >>> HAND-MAINTAINED TAIL — the generator preserves this line to EOF <<<
--
-- scripts/build-neon-baseline.mjs re-emits everything ABOVE this marker on
-- every run and copies this line to EOF verbatim (it refuses to write at all
-- if the marker is missing). Post-squash privilege decisions live here: every
-- migration past the squash line that issues GRANT/REVOKE appends its
-- statements below, by hand, in migration order.

-- ===========================================================================
-- post-0033 grants (0037–0046) — appended by audit 2026-08-22
--
-- The generated block above is the privilege model as of the 0033 squash line.
-- Everything since lives only in supabase/migrations/, so re-applying this file
-- after a Data API re-provision restored a five-migration-old privilege model:
-- new tables lost their grants (42501 on every read) and, worse, the audit's
-- own narrowing was silently undone. Derived by reading each migration
-- 0037–0046 in order; where a statement merely restates the block above
-- (`create or replace` preserving an ACL) it is kept anyway, because
-- GRANT/REVOKE are declarative and a partial record is the failure mode this
-- section exists to fix.
--
-- MUST STAY BELOW THE GENERATED SECTIONS. Several of the 0046 statements
-- narrow grants the generated block above still issues.
-- ===========================================================================

-- 0037 (households.auto_add_out_to_list) — no grants; table-level privileges
-- cover columns added later. Recorded so the gap is deliberate, not missing.

-- 0038 / 0040: clear_stale_out_items re-created (ACL preserved, restated).
REVOKE ALL ON FUNCTION public.clear_stale_out_items(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.clear_stale_out_items(uuid) TO authenticated;

-- 0039 (catalog_items.image_url / nutrition_source) — no grants, same reason
-- as 0037.

-- 0040: the food-outcomes ledger. Append-only by privilege as well as policy —
-- no UPDATE, no DELETE, for anyone.
REVOKE ALL ON TABLE public.food_outcomes FROM PUBLIC;
GRANT SELECT, INSERT ON TABLE public.food_outcomes TO authenticated;

-- 0041: adaptive shelf life. Corrections and resets are append-only; the
-- derived table is written only by the trigger, and DELETE is the Reset button.
REVOKE ALL ON TABLE public.shelf_life_corrections FROM PUBLIC;
GRANT SELECT, INSERT ON TABLE public.shelf_life_corrections TO authenticated;
REVOKE ALL ON TABLE public.shelf_life_resets FROM PUBLIC;
GRANT SELECT, INSERT ON TABLE public.shelf_life_resets TO authenticated;
REVOKE ALL ON TABLE public.household_shelf_life FROM PUBLIC;
GRANT SELECT, DELETE ON TABLE public.household_shelf_life TO authenticated;
REVOKE ALL ON FUNCTION public.clamp_correction_recorded_at() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.clamp_reset_at() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.recompute_household_shelf_life() FROM PUBLIC;

-- 0042 / 0043: claim_ai_call re-created twice; `create or replace` keeps
-- 0027's service-role-only ACL and neither migration issues a grant.

-- 0044: push_tickets is server-only — RLS with zero policies, and no privilege
-- for any client role. The Worker reaches it as the table owner.
REVOKE ALL ON TABLE public.push_tickets FROM PUBLIC;

-- 0045: invite links. No UPDATE for any client role anywhere — `use_count`
-- moves only inside join_household_by_invite. (The INSERT here is narrowed to a
-- column list by 0046 below.)
REVOKE ALL ON TABLE public.household_invites FROM PUBLIC;
GRANT SELECT, INSERT, DELETE ON TABLE public.household_invites TO authenticated;
REVOKE ALL ON FUNCTION public.household_join_gate(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.join_household_by_invite(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.join_household_by_invite(text) TO authenticated;

-- 0046: the audit's hardening pass. Everything below NARROWS what the block at
-- the top of this file grants, which is why the order matters.

-- SEC-02. TRUNCATE is not RLS-governed, and post-0036 no table has an anon
-- policy — so the unauthenticated role's grants admit nothing and should not
-- exist. Same role-exists loop as the migration, for the same portability
-- reason (`anon` on Supabase, `anonymous` on Neon).
do $$
declare
  v_role text;
  v_fn   text;
begin
  foreach v_role in array array['anon', 'anonymous', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = v_role) then
      execute format('revoke truncate on all tables in schema public from %I', v_role);
    end if;
  end loop;

  foreach v_role in array array['anon', 'anonymous'] loop
    if not exists (select 1 from pg_roles where rolname = v_role) then
      continue;
    end if;
    execute format('revoke all on all tables in schema public from %I', v_role);
    execute format('revoke all on all sequences in schema public from %I', v_role);
    for v_fn in
      select p.oid::regprocedure::text
        from pg_proc p
        join pg_namespace n on n.oid = p.pronamespace,
             aclexplode(p.proacl) a
       where n.nspname = 'public'
         and p.proacl is not null
         and a.grantee = (select r.oid from pg_roles r where r.rolname = v_role)
    loop
      execute format('revoke all on function %s from %I', v_fn, v_role);
    end loop;
  end loop;
end $$;

-- SCH-07. Privileges that contradicted their own policies.
REVOKE INSERT, UPDATE ON TABLE public.household_members FROM authenticated;
REVOKE INSERT ON TABLE public.households FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.catalog_items FROM authenticated;
REVOKE SELECT, UPDATE, DELETE ON TABLE public.recipe_reports FROM authenticated;
REVOKE INSERT, DELETE ON TABLE public.profiles FROM authenticated;

-- SEC-06. A policy scopes rows, never columns: the INSERT grant is the only
-- thing that can stop an owner choosing their own invite `token`.
REVOKE INSERT ON TABLE public.household_invites FROM authenticated;
GRANT INSERT (household_id, created_by, max_uses, expires_at) ON TABLE public.household_invites TO authenticated;

-- SCH-08/SEC-15. add_grocery_items re-created; ACL restated.
REVOKE ALL ON FUNCTION public.add_grocery_items(uuid, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.add_grocery_items(uuid, jsonb) TO authenticated;

-- SEC-06/SCH-09. The two clamp trigger functions: invoked by their triggers,
-- never by name.
REVOKE ALL ON FUNCTION public.clamp_invite_created_at() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.clamp_outcome_recorded_at() FROM PUBLIC;

-- SCH-19. The column-scoped profile read, minus `notify_digest` (written by
-- the client, read only by the digest sender as the table owner). Revoking the
-- table-level privilege also drops the column-level grants of the same type,
-- so the survivors are re-issued — 0007's own pattern.
--
-- **`bio` and `links` joined this list in 0054** (spec 51) rather than getting a
-- REVOKE/GRANT pair of their own further down: the revoke above them would drop
-- an additive grant issued earlier in this file, which is the same trap 0052's
-- `recipes` columns avoided by folding into 0050's lists. One list per table is
-- the only shape that cannot go stale by reordering.
--
-- STILL NOT HERE, and 0054 widened the ROW predicate to `using (true)` so each
-- omission now protects against every signed-in account rather than a
-- household: `expo_push_token` (0001, a capability token), `notify_digest`
-- (0046 SCH-19), `timezone` and `last_digest_at` (0044).
REVOKE SELECT ON TABLE public.profiles FROM authenticated;
GRANT SELECT (id, display_name, avatar_url, created_at, bio, links) ON TABLE public.profiles TO authenticated;

-- 0050: recipe ratings (spec 47). Own-rows table, plus THE END of the 0037
-- "table-level privileges cover columns added later" convenience for `recipes`:
-- the table-level INSERT/UPDATE grants at the top of this file are narrowed to
-- the author-editable columns, because a policy scopes rows and never columns
-- and an owner would otherwise write their own `rating_avg`/`rating_count`.
--
-- EVERY FUTURE AUTHOR-EDITABLE `recipes` COLUMN MUST BE ADDED TO BOTH LISTS
-- BELOW as well as to its own migration. `time_minutes`/`difficulty` (0052,
-- spec 49) were the first customers and are IN the lists rather than in a block
-- of their own: the REVOKE above them would drop an additive grant issued
-- earlier in this file, so one list is the only shape that cannot go stale by
-- reordering. A column missing here comes back as a 42501 on save the next time
-- this file is re-applied.
REVOKE ALL ON TABLE public.recipe_ratings FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.recipe_ratings TO authenticated;
REVOKE ALL ON FUNCTION public.recompute_recipe_rating(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.recipe_ratings_recompute() FROM PUBLIC;

REVOKE INSERT, UPDATE ON TABLE public.recipes FROM authenticated;
GRANT INSERT (owner_id, title, description, steps, servings, tags, photo_url, visibility, import_source, source_url, time_minutes, difficulty) ON TABLE public.recipes TO authenticated;
GRANT UPDATE (title, description, steps, servings, tags, photo_url, visibility, import_source, source_url, time_minutes, difficulty) ON TABLE public.recipes TO authenticated;

-- 0051: recipe folders (spec 48). Two own-data tables and nothing else — the
-- Favorites half of that spec is a client change with no SQL at all.
--
-- ITEMS GET NO UPDATE, for any role: the row is (folder, recipe, when), so the
-- only honest edits are filing and unfiling, and moving a recipe between
-- folders is delete + insert. Granting UPDATE here would silently reopen that.
REVOKE ALL ON TABLE public.recipe_folders FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.recipe_folders TO authenticated;
REVOKE ALL ON TABLE public.recipe_folder_items FROM PUBLIC;
GRANT SELECT, INSERT, DELETE ON TABLE public.recipe_folder_items TO authenticated;
REVOKE ALL ON FUNCTION public.recipe_folders_cap() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.recipe_folder_items_cap() FROM PUBLIC;

-- 0052: recipe time & difficulty (spec 49). The two columns are in the 0050
-- lists above; what belongs here is the floor function's ACL.
--
-- `recipe_min_difficulty` is called from inside SECURITY INVOKER trigger bodies,
-- so EXECUTE is checked against whoever is writing the recipe — without the
-- grant every difficulty save 42501s. It reads nothing and returns arithmetic
-- over its arguments. The two trigger functions are reached only by their
-- triggers and stay unreachable by name.
REVOKE ALL ON FUNCTION public.recipe_min_difficulty(integer, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.recipe_min_difficulty(integer, integer) TO authenticated;
REVOKE ALL ON FUNCTION public.recipes_difficulty_floor() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.recipe_ingredients_difficulty_floor() FROM PUBLIC;

-- 0053: column-scoped UPDATE on households and grocery_items ----------------
--
-- Both narrow the `GRANT ALL ... TO authenticated` lines at the top of this
-- file, so they MUST stay below them — and nothing after them may re-issue a
-- table-level REVOKE UPDATE on either table, which would drop the column
-- grants (the 0050 lesson, stated there for `recipes`).
--
-- households: a policy scopes rows, never columns, so table-wide UPDATE let an
-- owner PATCH `created_by` — the key the client's "home household" floor is
-- read from — as well as `id` and `created_at`. The four columns below are the
-- client's entire write surface (`HouseholdPatch` plus rotation's
-- `invite_code`). INSERT stays revoked from 0046.
REVOKE UPDATE ON TABLE public.households FROM authenticated;
GRANT UPDATE (name, invite_code, auto_clear_out_days, auto_add_out_to_list)
  ON TABLE public.households TO authenticated;

-- grocery_items: table-wide UPDATE walked around the membership check 0046 put
-- inside `add_grocery_items`, so a bare `PATCH {added_by}` forged the byline
-- the list renders. Every insert goes through that RPC and the sweep, both
-- SECURITY DEFINER, so revoking INSERT here costs nothing. SELECT and DELETE
-- are untouched — the list screen deletes rows directly.
REVOKE INSERT, UPDATE ON TABLE public.grocery_items FROM authenticated;
GRANT UPDATE (status, category) ON TABLE public.grocery_items TO authenticated;

-- 0054: creator profiles (spec 51). The widened `profiles` SELECT grant is IN
-- the SCH-19 block above, for the reason stated there. What belongs here is the
-- reports table and the links validator's ACL.
--
-- `profile_reports` is WRITE-ONLY for clients and column-scoped even then:
-- select/update/delete would let a reporter read the queue, and a table-level
-- INSERT would let them file a report that arrives pre-resolved. Revoke first,
-- so a replay of this file converges on exactly these three columns instead of
-- leaving behind whatever an earlier edit granted.
REVOKE ALL ON TABLE public.profile_reports FROM PUBLIC;
REVOKE ALL ON TABLE public.profile_reports FROM authenticated;
GRANT INSERT (profile_id, reporter_id, reason) ON TABLE public.profile_reports TO authenticated;

-- `profile_links_valid` is called from inside the `profiles_links_elements`
-- CHECK, which is evaluated as whoever is writing the row — so EXECUTE is
-- checked against the client, and without the grant every profile save 42501s
-- (0052's `recipe_min_difficulty` lesson, one table over).
REVOKE ALL ON FUNCTION public.profile_links_valid(jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.profile_links_valid(jsonb) TO authenticated;

-- service_role on post-0033 objects (audit 2026-08-22, SEC-13) --------------
--
-- The generated guarded block above only knows the baseline; these are the
-- same grants for objects that landed after the squash line, moved here when
-- the generator learned to emit that block itself. Same guard, same reason.
-- Safe to run last: nothing in this file revokes from service_role.
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    raise notice 'role service_role not present (Data API not provisioned) — skipping';
    return;
  end if;

  grant select, insert on table public.food_outcomes to service_role;
  grant select, insert on table public.shelf_life_corrections to service_role;
  grant select, insert on table public.shelf_life_resets to service_role;
  grant select, delete on table public.household_shelf_life to service_role;
  grant select, insert, update, delete on table public.push_tickets to service_role;
  grant select, insert, delete on table public.household_invites to service_role;
  grant select, insert, update, delete on table public.recipe_ratings to service_role;
  grant select, insert, update, delete on table public.recipe_folders to service_role;
  -- No UPDATE, deliberately — see the 0051 block above.
  grant select, insert, delete on table public.recipe_folder_items to service_role;
  -- 0052: service_role holds table-level ALL on `recipes` from the baseline, so
  -- it needs no column grants — only the floor function its writes will call.
  grant execute on function public.recipe_min_difficulty(integer, integer) to service_role;
  -- 0054: the admin queue reads reports as the table owner over
  -- NEON_DATABASE_URL, but service_role gets the `push_tickets` treatment for
  -- parity with every other server-side table here.
  grant select, insert, update, delete on table public.profile_reports to service_role;
  grant execute on function public.profile_links_valid(jsonb) to service_role;
  grant execute on function public.add_grocery_items(uuid, jsonb) to service_role;
  grant execute on function public.join_household_by_invite(text) to service_role;
end $$;
